In [1]:
import numpy as np

In [2]:
d = np.array([1, 2, 3, 4])
d.dtype#查看数组元素类型

dtype('int64')

In [5]:
d2 = np.array([1, 2, 3, 4], dtype=float)
d2.dtype

dtype('float64')

In [6]:
d.astype(float)#修改数组元素类型

array([1., 2., 3., 4.])

In [7]:
d

array([1, 2, 3, 4])

In [8]:
d3 = np.array([1, 2, 3.14, 5])
d3.dtype

dtype('float64')

In [10]:
d4 = np.array([1, 2, 3.14, 5], dtype=int)
d4.dtype

dtype('int64')

In [11]:
d4

array([1, 2, 3, 5])

In [12]:
d

array([1, 2, 3, 4])

In [13]:
d.shape

(4,)

In [14]:
dd = np.array([[1, 2, 3], [4, 5, 6]])
dd

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
dd.shape

(2, 3)

In [16]:
dd.size

6

In [18]:
d.ndim#查看数组得维度

1

In [19]:
dd.ndim

2

In [21]:
db = np.array([1, 2, 3, 4], ndmin=2)
db

array([[1, 2, 3, 4]])

In [22]:
db.ndim

2

In [24]:
dn = np.arange(24)
dn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
dn = dn.reshape(2, 3, 4)
dn

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])