## 矩阵

### 创建

In [1]:
y <- matrix(c(1, 2, 3, 4), nrow=2, ncol=2)
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [2]:
y[,2]

[1] 3 4

In [4]:
y <- matrix(nrow=2, ncol=2)
y[1, 1] <- 1
y[2, 1] <- 2
y[1, 2] <- 3
y[2, 2] <- 4
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [6]:
# byrow：矩阵元素按行排列
m <- matrix(c(1, 2, 3, 4, 5, 6), nrow=2, byrow=T)
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

### 一般矩阵运算

In [10]:
# 线性代数
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [8]:
y * 3

[,1] [,2]
[1,] 3     9  
[2,] 6    12

In [9]:
y + y

[,1] [,2]
[1,] 2    6   
[2,] 4    8

In [12]:
# 矩阵索引
z <- matrix(c(1, 2, 3, 4, 1, 1, 0, 0, 1, 0, 1, 0), nrow=4)
z

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 2    1    0   
[3,] 3    0    1   
[4,] 4    0    0

In [14]:
# 列提取
z[, 2:3]

[,1] [,2]
[1,] 1    1   
[2,] 1    0   
[3,] 0    1   
[4,] 0    0

In [15]:
y <- matrix(c(11, 21, 31, 12, 22, 32), nrow=3)
y

[,1] [,2]
[1,] 11   12  
[2,] 21   22  
[3,] 31   32

In [16]:
# 行提取
y[2:3, ]

[,1] [,2]
[1,] 21   22  
[2,] 31   32

In [17]:
y[2:3, 2]

[1] 22 32

In [20]:
# 矩阵赋值
y <- matrix(c(1, 2, 3, 4, 5, 6), nrow=3)
y

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [21]:
y[c(1, 3),] <- matrix(c(1, 1, 8, 12), nrow=2)

In [22]:
y

[,1] [,2]
[1,] 1     8  
[2,] 2     5  
[3,] 1    12

In [23]:
x <- matrix(nrow=3, ncol=3)
y <- matrix(c(4, 5, 2, 3), nrow=2)
y

[,1] [,2]
[1,] 4    2   
[2,] 5    3

In [24]:
x[2:3, 2:3] <- y
x

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA    4    2  
[3,] NA    5    3

In [25]:
# 负值索引排除某些元素
y

[,1] [,2]
[1,] 4    2   
[2,] 5    3

In [26]:
y[-2,]

[1] 4 2

In [27]:
# 矩阵元素筛选
x <- matrix(c(1, 2, 3, 2, 3, 4), nrow=3)
x

[,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4

In [28]:
j <- x[, 2] >= 3
j

[1] FALSE  TRUE  TRUE

In [29]:
x[j, ]

[,1] [,2]
[1,] 2    3   
[2,] 3    4

In [30]:
x

[,1] [,2]
[1,] 1    2   
[2,] 2    3   
[3,] 3    4

In [31]:
x[x[,2 ] >= 3,]

[,1] [,2]
[1,] 2    3   
[2,] 3    4

In [32]:
z <- c(5, 12, 13)
x[z %%2 == 1, ]

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [33]:
m <- matrix(c(1, 2, 3, 4, 5, 6), nrow=3)
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [34]:
m[m[,1]>1 & m[, 2]>5, ]

[1] 3 6

In [35]:
m <- matrix(c(5, 2, 9, -1, 10, 11), nrow=3)
m

[,1] [,2]
[1,] 5    -1  
[2,] 2    10  
[3,] 9    11

In [36]:
which(m>2)

[1] 1 3 5 6