## 向量

### 标量、向量、数组和矩阵

mode：同一向量中的所有元素必须是相同的模式

In [2]:
#添加、删除
x <- c(88,5,12,13)
x <- c(x[1:3], 168, x[4])
x

[1]  88   5  12 168  13

In [3]:
#长度
x <- c(1, 2, 4)
length(x)

[1] 3

In [4]:
first1 <- function(x){
    for (i in 1:length(x)){
        if (x[i] == 1) break # break 
    }
    return(i)
}

In [7]:
x <- c()
length(x)
1:length(x)

[1] 0

[1] 1 0

In [9]:
#矩阵和数组
m <- rbind(c(1, 4), c(2, 2)) # row bind
m

[,1] [,2]
[1,] 1    4   
[2,] 2    2

In [10]:
m <- cbind(c(1, 4), c(2, 2)) # row bind
m

[,1] [,2]
[1,] 1    2   
[2,] 4    2

In [11]:
m <- rbind(c(1, 2), c(3, 4))
m

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [12]:
m + 10:13

[,1] [,2]
[1,] 11   14  
[2,] 14   17

In [13]:
#特定元素申明
y <- vector(length=2)
y[1] <- 5
y[2] <- 12
y

[1]  5 12

In [14]:
#循环补齐
c(1, 2, 4) + c(6, 0, 9, 20, 22)

Warning message in c(1, 2, 4) + c(6, 0, 9, 20, 22):
“longer object length is not a multiple of shorter object length”


[1]  7  2 13 21 24

In [16]:
c(1, 2, 4, 1, 2) + c(6, 0, 9, 20, 22)

[1]  7  2 13 21 24

In [17]:
x <- rbind(c(1, 4), c(2, 5))
x

[,1] [,2]
[1,] 1    4   
[2,] 2    5

In [18]:
x+c(1,2)

[,1] [,2]
[1,] 2    5   
[2,] 4    7

### 常用的向量运算

In [19]:
#向量运算和逻辑运算
2 + 3

[1] 5

In [20]:
"+"(2, 3)

[1] 5

In [21]:
x <- c(1, 2, 4)
x + c(5, 0, -1)

[1] 6 2 3

In [23]:
x*c(5, 0, -1)

[1]  5  0 -4

In [24]:
x/c(5, 4, -1)

[1]  0.2  0.5 -4.0

In [25]:
x %% c(5, 4, -1)

[1] 1 2 0

In [26]:
# 向量索引
y <- c(1.2, 3.9, 0.4, 0.12)
y[c(1, 3)] # extract elements 1 and 3

[1] 1.2 0.4

In [27]:
y[2:3]

[1] 3.9 0.4

In [28]:
v <- 3:4
y[v]

[1] 0.40 0.12

In [30]:
# 元素运行重复
x <- c(4, 2, 17, 5)
y <- x[c(1, 1, 3)]
y

[1]  4  4 17

In [31]:
# 负数下标代表吧相应元素剔除
z <- c(5, 12, 13)
z[-1]

[1] 12 13

In [32]:
z[-1:-2]

[1] 13

In [33]:
z <- c(5, 12, 13)
z[1:(length(z) - 1)]

[1]  5 12

In [35]:
z[-length(z)]

[1]  5 12

In [36]:
#用：运算符创建向量
5:8

[1] 5 6 7 8

In [38]:
#冒号运算符优先级高于减号
i <- 2
1:i-1 # means (1:i) - 1

[1] 0 1

In [39]:
1:(i-1)

[1] 1

In [41]:
# 使用seq()创建向量，生成等差序列
seq(from=12, to=30, by=3)

[1] 12 15 18 21 24 27 30

In [42]:
#间隔可以不为整数
seq(from=1.1, to=2, length=10)

[1] 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

In [43]:
#空向量问题
x <- c(5, 12, 13)
x

[1]  5 12 13

In [44]:
seq(x)

[1] 1 2 3

In [45]:
x <- c()
x

NULL

In [46]:
seq(x)

integer(0)

In [50]:
#使用rep()重复向量常数， rep(x, times)
x <- rep(8, 4)
x

[1] 8 8 8 8

In [48]:
rep(c(5, 12, 13), 3)

[1]  5 12 13  5 12 13  5 12 13

In [49]:
rep(1:3, 2)

[1] 1 2 3 1 2 3

In [52]:
# each 指定x交替重复次数
rep(c(5, 12, 13), each=2)

[1]  5  5 12 12 13 13

In [53]:
# all()和any()
x <- 1:10
any(x>8)

[1] TRUE

In [54]:
any(x > 88)

[1] FALSE

In [55]:
all(x > 88)

[1] FALSE

In [56]:
any(x > 0)

[1] TRUE

In [57]:
x>8

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE