## 向量

### 标量、向量、数组和矩阵

mode：同一向量中的所有元素必须是相同的模式

In [2]:
#添加、删除
x <- c(88,5,12,13)
x <- c(x[1:3], 168, x[4])
x

[1]  88   5  12 168  13

In [3]:
#长度
x <- c(1, 2, 4)
length(x)

[1] 3

In [4]:
first1 <- function(x){
    for (i in 1:length(x)){
        if (x[i] == 1) break # break 
    }
    return(i)
}

In [7]:
x <- c()
length(x)
1:length(x)

[1] 0

[1] 1 0

In [9]:
#矩阵和数组
m <- rbind(c(1, 4), c(2, 2)) # row bind
m

[,1] [,2]
[1,] 1    4   
[2,] 2    2

In [10]:
m <- cbind(c(1, 4), c(2, 2)) # row bind
m

[,1] [,2]
[1,] 1    2   
[2,] 4    2

In [11]:
m <- rbind(c(1, 2), c(3, 4))
m

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [12]:
m + 10:13

[,1] [,2]
[1,] 11   14  
[2,] 14   17

In [13]:
#特定元素申明
y <- vector(length=2)
y[1] <- 5
y[2] <- 12
y

[1]  5 12

In [14]:
#循环补齐
c(1, 2, 4) + c(6, 0, 9, 20, 22)

Warning message in c(1, 2, 4) + c(6, 0, 9, 20, 22):
“longer object length is not a multiple of shorter object length”


[1]  7  2 13 21 24

In [16]:
c(1, 2, 4, 1, 2) + c(6, 0, 9, 20, 22)

[1]  7  2 13 21 24

In [17]:
x <- rbind(c(1, 4), c(2, 5))
x

[,1] [,2]
[1,] 1    4   
[2,] 2    5

In [18]:
x+c(1,2)

[,1] [,2]
[1,] 2    5   
[2,] 4    7

### 常用的向量运算

In [19]:
#向量运算和逻辑运算
2 + 3

[1] 5

In [20]:
"+"(2, 3)

[1] 5

In [21]:
x <- c(1, 2, 4)
x + c(5, 0, -1)

[1] 6 2 3

In [23]:
x*c(5, 0, -1)

[1]  5  0 -4

In [24]:
x/c(5, 4, -1)

[1]  0.2  0.5 -4.0

In [25]:
x %% c(5, 4, -1)

[1] 1 2 0

In [26]:
# 向量索引
y <- c(1.2, 3.9, 0.4, 0.12)
y[c(1, 3)] # extract elements 1 and 3

[1] 1.2 0.4

In [27]:
y[2:3]

[1] 3.9 0.4

In [28]:
v <- 3:4
y[v]

[1] 0.40 0.12

In [30]:
# 元素运行重复
x <- c(4, 2, 17, 5)
y <- x[c(1, 1, 3)]
y

[1]  4  4 17

In [31]:
# 负数下标代表吧相应元素剔除
z <- c(5, 12, 13)
z[-1]

[1] 12 13

In [32]:
z[-1:-2]

[1] 13

In [33]:
z <- c(5, 12, 13)
z[1:(length(z) - 1)]

[1]  5 12

In [35]:
z[-length(z)]

[1]  5 12

In [36]:
#用：运算符创建向量
5:8

[1] 5 6 7 8

In [38]:
#冒号运算符优先级高于减号
i <- 2
1:i-1 # means (1:i) - 1

[1] 0 1

In [39]:
1:(i-1)

[1] 1

In [41]:
# 使用seq()创建向量，生成等差序列
seq(from=12, to=30, by=3)

[1] 12 15 18 21 24 27 30

In [42]:
#间隔可以不为整数
seq(from=1.1, to=2, length=10)

[1] 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

In [43]:
#空向量问题
x <- c(5, 12, 13)
x

[1]  5 12 13

In [44]:
seq(x)

[1] 1 2 3

In [45]:
x <- c()
x

NULL

In [46]:
seq(x)

integer(0)

In [50]:
#使用rep()重复向量常数， rep(x, times)
x <- rep(8, 4)
x

[1] 8 8 8 8

In [48]:
rep(c(5, 12, 13), 3)

[1]  5 12 13  5 12 13  5 12 13

In [49]:
rep(1:3, 2)

[1] 1 2 3 1 2 3

In [52]:
# each 指定x交替重复次数
rep(c(5, 12, 13), each=2)

[1]  5  5 12 12 13 13

In [53]:
# all()和any()
x <- 1:10
any(x>8)

[1] TRUE

In [54]:
any(x > 88)

[1] FALSE

In [55]:
all(x > 88)

[1] FALSE

In [56]:
any(x > 0)

[1] TRUE

In [57]:
x>8

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE

In [1]:
#扩展案例：寻找连续出现1的游程
findruns <- function(x,k){
    n <- length(x)
    runs <- NULL
    for (i in 1:(n-k+1)){
        if (all(x[i:(i+k-1)]==1)) runs <- c(runs,i)
    }
    return(runs)
}

In [2]:
y <- c(1, 0, 0, 1, 1, 1, 0, 1, 1)
findruns(y, 3)

[1] 4

In [3]:
findruns(y,2)

[1] 4 5 8

In [4]:
findruns(y, 6)

NULL

In [5]:
#预先分配内存空间
findruns1 <- function(x, k){
    n <- length(x)
    runs <- vector(length=n)#提前分配内存空间
    count <- 0
    for (i in 1:(n-k+1)){
        if (all(x[i:(i+k -1)] == 1)){
            count <- count + 1
            runs[count] <- 1
        }
    }
    if (count > 0){
        runs <- runs[1:count]
    }else runs <- NULL
    return(runs)
}

In [6]:
y <- c(1, 0, 0, 1, 1, 1, 0, 1, 1)
findruns(y, 3)

[1] 4

In [7]:
#扩展案例：预测离散值时间序列
preda <- function(x,k){
    n <- length(x)
    k2 <- k/2
    pred <- vector(length=n-k)
    for (i in 1:(n-k)){
        if (sum(x[i:(i+(k-1))]) >= k2) pred[i] <- 1 else pred[i] <- 0
    }
    return (mean(abs(pred-x[(k+1):n])))
}

In [8]:
#利用上一步的计算结果
predb <- function(x,k){
    n <- length(x)
    k2 <- k/2
    pred <- vector(length=n-k)
    sm <- sum(x[1:k])
    if (sm >= k2) pred[1] <- 1 else pred[1] <- 0
    if (n-k >= 2){
        for (i in 2:(n-k)){
            sm <- sm + x[i+k-1] - x[i-1]
            if (sm >= k2) pred[i] <- 1 else pred[i] <- 0
        }
    }
    return(mean(abs(pred-x[(k+1):n])))
}

In [9]:
#累积和(cumulative sums)
y <- c(5, 2, -3, 8)
cumsum(y)

[1]  5  7  4 12

In [10]:
predc <- function(x,k){
    n <- length(x)
    k2 <- k/2
    pred <- vector(length=n-k)
    csx <- c(0, cumsum(x))
    for (i in 1:(n-k)){
        if (csx[i+k] - csx[i] >= k2) pred[i] <- 1 else pred[i] <- 0
    }
    return(mean(abs(pred - x[(k+1):n])))
}

### 向量化运算符

In [1]:
#向量输入、输出
u <- c(5, 2, 8)
v <- c(1, 3, 9)
u > v

[1]  TRUE FALSE FALSE

In [2]:
w <- function(x) return(x+1)
w(u)

[1] 6 3 9

In [3]:
sqrt(1:9)

[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
[9] 3.000000

In [4]:
y <- c(1.2, 3.9, 0.4)
z <- round(y)
z

[1] 1 4 0

In [5]:
#向量输入、矩阵输出
z12 <- function(z) return(c(z, z^2))

In [6]:
x <- 1:8
z12(x)

[1]  1  2  3  4  5  6  7  8  1  4  9 16 25 36 49 64

In [7]:
matrix(z12(x), ncol=2)

[,1] [,2]
[1,] 1     1  
[2,] 2     4  
[3,] 3     9  
[4,] 4    16  
[5,] 5    25  
[6,] 6    36  
[7,] 7    49  
[8,] 8    64

In [8]:
#sapply() (simplify apply) sapply(x, f)即对x的每一个元素使用函数f，并将结果转换成矩阵
z12 <- function(z) return(c(z, z^2))
sapply(1:8, z12)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3     4    5    6    7    8  
[2,] 1    4    9    16   25   36   49   64

### NA and NULL

In [9]:
# NA的使用
x <- c(88, NA, 12, 168, 13)
x

[1]  88  NA  12 168  13

In [10]:
mean(x)

[1] NA

In [11]:
mean(x, na.rm=T)

[1] 70.25

In [13]:
x <- c(88, NULL, 12, 168, 13)
mean(x)

[1] 70.25

In [15]:
# NA的值有不同的模式
x <- c(5, NA, 12)
mode(x[1])

[1] "numeric"

In [16]:
mode(x[2])

[1] "numeric"

In [17]:
y <- c('abc', 'def', NA)
mode(y[2])

[1] "character"

In [18]:
mode(y[3])

[1] "character"

In [19]:
# NULL 使用
# build up a vector of the even numbers in 1:10
z <- NULL
for (i in 1:10) if (i %% 2 ==0) z <- c(z, i)
z

[1]  2  4  6  8 10

In [20]:
# 多余NA
z <- NA
for (i in 1:10) if (i %% 2 ==0) z <- c(z, i)
z

[1] NA  2  4  6  8 10

In [22]:
# 计数
u <- NULL
length(u)

[1] 0

In [23]:
v <- NA
length(v)

[1] 1

### 筛选

In [25]:
z <- c(5, 2, -3, 8)
w <- z[z*z > 8]
w

[1]  5 -3  8

In [26]:
z <- c(5, 2, -3, 8)
z*z > 8

[1]  TRUE FALSE  TRUE  TRUE

In [27]:
z[c(TRUE, FALSE, TRUE, TRUE)]

[1]  5 -3  8

In [29]:
#使用一个向量决定筛选另一个向量的索引
z <- c(5, 2, -3, 8)
j <- z*z > 8
j

[1]  TRUE FALSE  TRUE  TRUE

In [30]:
y <- c(1, 2, 30, 5)
y[j]

[1]  1 30  5

In [31]:
z <- c(5, 2, -3, 8)
y <- c(1, 2, 30, 5)
y[z*z > 8]

[1]  1 30  5

In [32]:
#将所有比3大的元素替换为0
x[x > 3] <- 0

In [33]:
x <- c(1, 3, 8, 2, 20)
x[x > 3] <- 0
x

[1] 1 3 0 2 0

In [34]:
# 使用subset()函数筛选；NA值处理
x <- c(6, 1:3, NA, 12)
x

[1]  6  1  2  3 NA 12

In [35]:
x[x > 5]

[1]  6 NA 12

In [36]:
subset(x, x>5)

[1]  6 12

In [37]:
#which(): 满足条件元素所在得位置
z <- c(5, 2, -3, 8)
which(z*z > 8)

[1] 1 3 4

### ifelse()

In [38]:
# ifelse(b, u, v)
x <- 1:10
y <- ifelse(x %% 2 == 0, 5, 12)
y

[1] 12  5 12  5 12  5 12  5 12  5

In [40]:
x <- c(5, 2, 9, 12)
y <- ifelse(x > 6, 2*x, 3*x)
y

[1] 15  6 18 24