In [1]:
import numpy as np

In [2]:
b = np.linspace(0, 100, 5)
b

array([  0.,  25.,  50.,  75., 100.])

In [3]:
b[3]

75.0

In [4]:
c = np.logspace(1, 3, 12).reshape((3, 4))
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [5]:
c[1]

array([ 53.36699231,  81.11308308, 123.28467394, 187.38174229])

In [6]:
c[1][2]

123.28467394420659

In [7]:
c[1, 2]

123.28467394420659

In [9]:
lst = [1, 2, 3]
lst[0] = 100
lst

[100, 2, 3]

In [11]:
b[1] = 100
b

array([  0., 100.,  50.,  75., 100.])

In [12]:
c[1, 2] = 100
c


array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  100.        ,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [13]:
b

array([  0., 100.,  50.,  75., 100.])

In [14]:
b[[0, 2]]

array([ 0., 50.])

In [15]:
b[[2]]

array([50.])

In [16]:
b[2]

50.0

In [18]:
c[[0,2]]

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [19]:
c[[0, 2], [1, 2]]

array([ 15.19911083, 657.93322466])

In [20]:
c[[1, 2, 1, 2]]

array([[  53.36699231,   81.11308308,  100.        ,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ],
       [  53.36699231,   81.11308308,  100.        ,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [22]:
v = np.array([0, 1, 3])
r= b[v]
r

array([  0., 100.,  75.])

In [23]:
b

array([  0., 100.,  50.,  75., 100.])

In [24]:
t = b==50
t

array([False, False,  True, False, False])

In [25]:
b[t]

array([50.])

In [26]:
e = np.arange(10).reshape((2,5))
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
t = e%2 == 0
t

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [28]:
e[t]

array([0, 2, 4, 6, 8])

In [29]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
b = a[2: 8]
b

array([12, 13, 14, 15, 16, 17])

In [32]:
a[: : 2]

array([10, 12, 14, 16, 18])

In [33]:
b = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [34]:
b[1:4]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [35]:
b[1:4, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [36]:
b[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [37]:
b[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])