四则运算、比较运算、逻辑运算

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a * 3

array([3, 6, 9])

In [5]:
a +10

array([11, 12, 13])

In [6]:
a - 10

array([-9, -8, -7])

In [7]:
 a / 10 

array([0.1, 0.2, 0.3])

In [8]:
b = a + 10

In [9]:
b

array([11, 12, 13])

In [10]:
a + b

array([12, 14, 16])

In [11]:
a

array([1, 2, 3])

In [12]:
b

array([11, 12, 13])

In [13]:
a * b

array([11, 24, 39])

In [14]:
a = np.arange(10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
m = np.arange(5)

In [16]:
m

array([0, 1, 2, 3, 4])

In [17]:
a + m#自动补齐

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [18]:
n = np.arange(1, 3).reshape((-1, 1))
n

array([[1],
       [2]])

In [19]:
a + n

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [20]:
np.array([6, 3, 4]) > np.array([3, 5, 2])

array([ True, False,  True])

In [21]:
np.array([6, 3, 4]) > np.array([3, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
np.logical_or(np.array([False, True]), np.array([True, False]))

array([ True,  True])

In [23]:
a = np.array([3, 6, 9])
b = np.array([4, 5, 8])


In [24]:
np.any(a < b)

True

In [25]:
(a < b).any()

True

In [26]:
np.all(a < b)

False

In [27]:
alpha = np.linspace(-1, 1, 11)

In [28]:
alpha

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [29]:
y = np.sin(np.pi * alpha)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [30]:
np.round(y, 2)

array([-0.  , -0.59, -0.95, -0.95, -0.59,  0.  ,  0.59,  0.95,  0.95,
        0.59,  0.  ])

普通函数转化成数组通用函数

In [31]:
def bmi(h, w):
    bmi_index = w / h **2
    if bmi_index > 18 and bmi_index < 25:
        return 0
    elif bmi_index <= 18:
        return -1
    else:
        return 1

In [32]:
bmi(1.63, 55)

0

In [34]:
h = (2.2 - 1.4)*np.random.random_sample((10, )) + 1.4
h = np.round(h, 2)
h

array([1.87, 1.66, 1.83, 1.98, 1.59, 2.18, 1.99, 2.16, 1.54, 2.11])

In [35]:
w = (96 - 30)*np.random.random_sample((10, )) + 30
w = np.round(w, 2)
w

array([69.63, 56.17, 63.32, 47.77, 90.02, 74.14, 84.71, 34.49, 77.95,
       86.14])

In [36]:
bmi(w, h)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
bmi_ufunc = np.frompyfunc(bmi, 2, 1)#2表示两个输入， 1表示一个输出
bmi_ufunc(h, w)

array([0, 0, 0, -1, 1, -1, 0, -1, 1, 0], dtype=object)