生成正态分布数据

In [1]:
import numpy as np

In [2]:
mu, sigma = 0.0, 1.0

In [3]:
g = np.random.normal(loc=mu, scale=sigma, size=1000)
g

array([-7.73997260e-01, -7.03788993e-01, -6.78168602e-01, -2.09791228e+00,
        5.38312999e-01, -9.01885244e-01, -2.53089703e+00, -8.38865255e-01,
        1.79869717e-01, -3.57129792e-01, -7.14024169e-01, -1.57033943e-01,
       -6.39879993e-02, -8.85602997e-01, -5.86582957e-01,  5.12822009e-02,
        9.42486068e-01,  2.06503218e-01, -9.35687886e-02, -1.55322328e+00,
       -2.21354844e-01,  4.77349883e-01,  1.36797368e+00,  7.26278354e-01,
       -2.33835724e-01, -1.72934429e-01,  4.51952566e-01,  1.51222601e+00,
       -5.94671416e-02, -1.68955437e-01,  4.84909781e-01,  1.88694560e-01,
       -1.12947764e+00,  1.49614978e+00,  6.42369757e-02,  1.62981251e+00,
       -5.49831083e-02, -5.09016324e-01,  5.77283127e-01, -2.82364616e-01,
       -1.07707393e+00, -9.72647149e-01, -8.88767244e-02, -1.59980652e+00,
       -1.60366119e+00, -4.09630925e-01, -5.98710957e-01, -4.65711205e-01,
       -1.32756331e+00,  1.26292531e+00, -2.17884092e+00,  2.92538142e-01,
        6.60144733e-01,  

In [4]:
g1 = np.random.randn(1000)
g1

array([ 3.32776218e-01, -4.71093479e-01,  5.47563909e-01, -1.62790927e+00,
        2.78365871e-01, -6.81151408e-01, -1.11405067e+00,  9.41480881e-03,
       -7.26864334e-01, -1.06964682e+00, -8.51037142e-01,  4.80552525e-01,
       -1.06307636e+00, -7.51863200e-03,  6.05550218e-01,  8.58646235e-01,
        1.62425943e-01, -1.13997234e+00, -3.12935184e-01, -6.68428959e-01,
        5.25142326e-01,  8.33226779e-01,  9.83033095e-03, -8.08067896e-01,
       -8.25013557e-01,  2.78272311e-01, -9.53485340e-01, -9.78042164e-01,
        3.03957919e-01,  1.43189139e+00,  1.95298651e-01, -3.43550585e-01,
       -3.04288395e-03,  1.46029029e+00,  7.46481339e-02,  3.36802434e-01,
        1.70330618e-01,  2.64381141e+00, -1.22876583e+00,  2.17438827e-01,
       -4.47172376e-01, -1.78806648e+00,  8.61545253e-01,  7.39466232e-01,
       -2.05269017e+00,  4.98738285e-01, -5.00723679e-01,  8.99293941e-01,
       -2.85822688e-01, -7.72564413e-01, -7.34844882e-01,  4.69391526e-01,
        7.40585347e-01, -

In [5]:
g = (g - g.min()) / 10
phy = np.round(((100.1 - 20) * g + 20), 1)
g1 = (g1 - g1.min()) / 10
mat = np.round(((100.1 - 20) * g + 20), 1)


In [7]:
phy

array([37.9, 38.5, 38.7, 27.3, 48.4, 36.9, 23.8, 37.4, 45.5, 41.2, 38.4,
       42.8, 43.6, 37. , 39.4, 44.5, 51.6, 45.7, 43.3, 31.7, 42.3, 47.9,
       55.1, 49.9, 42.2, 42.7, 47.7, 56.2, 43.6, 42.7, 48. , 45.6, 35. ,
       56.1, 44.6, 57.1, 43.7, 40. , 48.7, 41.8, 35.5, 36.3, 43.4, 31.3,
       31.2, 40.8, 39.3, 40.4, 33.5, 54.2, 26.6, 46.4, 49.4, 44.2, 43.4,
       33.3, 49.8, 57.3, 43.4, 51.4, 40.2, 52.4, 58. , 43.1, 37.4, 48.6,
       42.2, 55.1, 46.6, 39.8, 35.2, 43.7, 50.4, 52.5, 55.9, 47. , 35.7,
       33.2, 48.6, 45.4, 43.7, 47.7, 33.5, 32.8, 47.7, 46.7, 40.7, 32. ,
       45.4, 49.1, 36. , 51.7, 60. , 39.4, 44.7, 47.8, 46.6, 39.4, 44.8,
       49.7, 50.5, 36. , 48.7, 45.4, 50.1, 53.4, 39.7, 27.4, 46.4, 43.4,
       48.6, 30.2, 30.6, 36.8, 37.2, 34.7, 40.3, 34.8, 33. , 41.2, 49.2,
       46.5, 47.6, 40.5, 38.2, 43. , 22.5, 47.6, 49.7, 51.7, 43.2, 36.8,
       53.1, 49.8, 34.5, 56.4, 47.4, 59.6, 45.8, 50.3, 52.8, 46.7, 53. ,
       47.9, 47.1, 32.1, 26.1, 48.6, 47. , 33.7, 41

In [8]:
mat

array([37.9, 38.5, 38.7, 27.3, 48.4, 36.9, 23.8, 37.4, 45.5, 41.2, 38.4,
       42.8, 43.6, 37. , 39.4, 44.5, 51.6, 45.7, 43.3, 31.7, 42.3, 47.9,
       55.1, 49.9, 42.2, 42.7, 47.7, 56.2, 43.6, 42.7, 48. , 45.6, 35. ,
       56.1, 44.6, 57.1, 43.7, 40. , 48.7, 41.8, 35.5, 36.3, 43.4, 31.3,
       31.2, 40.8, 39.3, 40.4, 33.5, 54.2, 26.6, 46.4, 49.4, 44.2, 43.4,
       33.3, 49.8, 57.3, 43.4, 51.4, 40.2, 52.4, 58. , 43.1, 37.4, 48.6,
       42.2, 55.1, 46.6, 39.8, 35.2, 43.7, 50.4, 52.5, 55.9, 47. , 35.7,
       33.2, 48.6, 45.4, 43.7, 47.7, 33.5, 32.8, 47.7, 46.7, 40.7, 32. ,
       45.4, 49.1, 36. , 51.7, 60. , 39.4, 44.7, 47.8, 46.6, 39.4, 44.8,
       49.7, 50.5, 36. , 48.7, 45.4, 50.1, 53.4, 39.7, 27.4, 46.4, 43.4,
       48.6, 30.2, 30.6, 36.8, 37.2, 34.7, 40.3, 34.8, 33. , 41.2, 49.2,
       46.5, 47.6, 40.5, 38.2, 43. , 22.5, 47.6, 49.7, 51.7, 43.2, 36.8,
       53.1, 49.8, 34.5, 56.4, 47.4, 59.6, 45.8, 50.3, 52.8, 46.7, 53. ,
       47.9, 47.1, 32.1, 26.1, 48.6, 47. , 33.7, 41

In [9]:
np.mean(phy)#平均数

43.81510000000001

In [10]:
np.std(phy)#标准差

7.809199830328328

In [11]:
np.min(phy), np.max(phy)

(20.0, 66.3)

In [12]:
np.percentile(phy, 80)#百分位数

50.4

In [13]:
np.median(phy)#中位数

44.150000000000006

In [14]:
phy[phy > np.mean(phy)]

array([48.4, 45.5, 44.5, 51.6, 45.7, 47.9, 55.1, 49.9, 47.7, 56.2, 48. ,
       45.6, 56.1, 44.6, 57.1, 48.7, 54.2, 46.4, 49.4, 44.2, 49.8, 57.3,
       51.4, 52.4, 58. , 48.6, 55.1, 46.6, 50.4, 52.5, 55.9, 47. , 48.6,
       45.4, 47.7, 47.7, 46.7, 45.4, 49.1, 51.7, 60. , 44.7, 47.8, 46.6,
       44.8, 49.7, 50.5, 48.7, 45.4, 50.1, 53.4, 46.4, 48.6, 49.2, 46.5,
       47.6, 47.6, 49.7, 51.7, 53.1, 49.8, 56.4, 47.4, 59.6, 45.8, 50.3,
       52.8, 46.7, 53. , 47.9, 47.1, 48.6, 47. , 47.5, 53.8, 48.6, 45.1,
       54.9, 45.7, 44.1, 55.7, 56.4, 45.1, 48.5, 56.4, 55.8, 53.1, 52.1,
       45.5, 44.2, 45.4, 56.3, 45. , 44. , 62.2, 53.4, 43.9, 62. , 50.4,
       50.9, 44.8, 44.6, 44.8, 53.4, 49.3, 56.5, 45.7, 46.1, 50.4, 44.6,
       47.8, 50.2, 45.3, 44. , 61. , 46.7, 57.7, 48.8, 45.3, 44.8, 52.4,
       48. , 47.8, 47.7, 50.6, 61.8, 48.5, 44.8, 50.1, 47.1, 51.2, 48.5,
       53.4, 46.9, 49.3, 49.7, 51. , 47.1, 44.3, 49.1, 44.9, 49.2, 56.3,
       43.9, 46.7, 45.1, 44.2, 50.9, 50.1, 44.2, 48

In [15]:
np.where(phy > mat, 1, -1)#大于则返回1， 否则返回-1

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [17]:
np.where(phy > phy.mean())#返回满足条件的索引

(array([  4,   8,  15,  16,  17,  21,  22,  23,  26,  27,  30,  31,  33,
         34,  35,  38,  49,  51,  52,  53,  56,  57,  59,  61,  62,  65,
         67,  68,  72,  73,  74,  75,  78,  79,  81,  84,  85,  88,  89,
         91,  92,  94,  95,  96,  98,  99, 100, 102, 103, 104, 105, 108,
        110, 120, 121, 122, 127, 128, 129, 132, 133, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 147, 148, 151, 156, 158, 159, 160,
        161, 162, 165, 166, 168, 169, 170, 171, 173, 174, 176, 181, 182,
        183, 184, 185, 186, 188, 189, 190, 192, 193, 195, 196, 200, 201,
        208, 213, 215, 218, 219, 220, 222, 223, 225, 226, 227, 229, 230,
        237, 239, 245, 246, 247, 248, 250, 251, 255, 257, 258, 259, 260,
        261, 262, 263, 265, 266, 267, 268, 270, 277, 278, 279, 280, 281,
        282, 283, 285, 286, 287, 289, 290, 291, 296, 297, 298, 301, 303,
        304, 309, 314, 315, 317, 319, 324, 327, 329, 330, 331, 332, 333,
        335, 336, 337, 339, 342, 343, 344, 347, 349

多项式

In [20]:
a = np.array([1, -2, 1])#降序排列多项式系数
p = np.poly1d(a)
p# x**2 - 2x + 1 

poly1d([ 1, -2,  1])

In [21]:
p(1)# 1**2 - 2*1 + 1

0

In [23]:
#f(x) = (x-1)**2 + 3(x-1) + 1
g = np.poly1d([1, 3, 1])
f = lambda x: g(x-1)
f(0)

-1

In [24]:
a 

array([ 1, -2,  1])

In [26]:
p2 = np.poly1d(a, r=True)#r=True，生成以a为根的多项式
p2

poly1d([ 1.,  0., -3.,  2.])

In [27]:
print(p2)

   3
1 x - 3 x + 2


In [28]:
p3 = np.poly1d(a, r=True, variable="m")#修改多项式变量名称，默认为x

In [29]:
print(p3)

   3
1 m - 3 m + 2


In [30]:
print(p)
print(p2)

   2
1 x - 2 x + 1
   3
1 x - 3 x + 2


In [31]:
print(p + p2)

   3     2
1 x + 1 x - 5 x + 3


In [32]:
print(p * p2)

   5     4     3     2
1 x - 2 x - 2 x + 8 x - 7 x + 2


In [33]:
p.deriv()#多项式求导

poly1d([ 2, -2])