In [2]:
import numpy as np

In [2]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a = np.arange(10)
b = np.reshape(a, (2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
c = b.reshape((-1, 1))#-1 表示由numpy自行推断0轴元素的个数
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
np.reshape(b, (10,))#得到的是一维数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.reshape(b, (1, 10))#得到的是二维数组

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
b.shape

(2, 5)

In [9]:
b.shape = (1, 10)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
b.shape = (10, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
b.flatten()#数组扁平化

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ne = np.ravel(b)# ne 和 b 共用一个原始数组，修改ne种的值，b的值也会发生变化
ne

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ne[1] = 111

In [14]:
b

array([[  0],
       [111],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [3]:
data = np.arange(0, 5)
c = data[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [4]:
data[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

数组组合

In [5]:
a = np.arange(9).reshape((3, 3))
b = np.arange(12).reshape((3, 4))
c = np.arange(15).reshape(3, 5)

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [9]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [10]:
np.vstack((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [11]:
np.vstack((a, b.T))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [12]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
np.concatenate((a, b.T), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [15]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
np.split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [17]:
np.split(a, 2, axis= 1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [18]:
np.hsplit(a, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [19]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]